;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(isearch-delete-char
                               isearch-backward-regexp
                               dot-mode-execute
                               maybe-fill-paragraph
                               isearch-exit-other-end
                               sgml-slash
                               sacha/search-word-forward
                               org-metaleft
                               org-insert-todo-heading
                               bm-toggle
                               bm-next
                               org-yank
                               org-return-indent
                               org-metaright
                               org-force-self-insert
                               wgrep-finish-edit
                               org-kill-line
                               kmacro-end-or-call-macro
                               cua-cut-region
                               org-beginning-of-line
                               ace-jump-move
                               python-shift-left
                               orgtbl-hijacker-command-102
                               isearch-exit
                               isearch-printing-char
                               replace-string
                               cua-delete-region
                               org-table-copy-down
                               python-shift-right
                               transpose-words
                               org-cycle-agenda-files
                               cua-paste-pop
                               save-thing-at-point-select
                               save-thing-at-point-exit
                               save-thing-at-point
                               comment-dwim-line
                               yas/expand
                               python-electric-colon
                               python-backspace
                               orgtbl-hijacker-command-100
                               org-end-of-line
                               org-self-insert-command
                               orgtbl-hijacker-command-16
                               cua-paste
                               orgtbl-hijacker-command-101
                               org-delete-char
                               open-next-line
                               org-delete-backward-char
                               quoted-insert
                               protect-dash
                               protect-equal
                               protect-underscore
                               kill-region
                               isearch-abort
                               goto-last-change
                               goto-match-paren
                               back-to-indentation-or-beginning
                               orgtbl-self-insert-command
                               skeleton-pair-insert-maybe))

(setq mc/cmds-to-run-once '(ido-find-file
                            python-send-buffer
                            cua-clear-rectangle-mark
                            cua-set-rectangle-mark
                            use-emacs-keys
                            copy-rectangle-to-register
                            org-cycle
                            sh-maybe-here-document
                            eval-print-last-sexp
                            beginning-of-buffer
                            end-of-buffer
                            previous-error-no-select
                            anything
                            fill-paragraph
                            smex
                            isearch-other-control-char
                            tags-loop-continue
                            ace-jump-done
                            ace-jump-char-mode
                            ac-expand
                            isearch-other-meta-char
                            isearch-forward-regexp
                            rs-mark-paragraph
                            set-rectangular-region-anchor
                            switch-to-previous-buffer))

                            
                               