;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(open-next-line
                               org-delete-backward-char
                               quoted-insert
                               protect-dash
                               protect-equal
                               protect-underscore
                               kill-region
                               isearch-abort
                               goto-last-change
                               goto-match-paren
                               back-to-indentation-or-beginning
                               orgtbl-self-insert-command
                               skeleton-pair-insert-maybe))

(setq mc/cmds-to-run-once '(previous-error-no-select
                            anything
                            fill-paragraph
                            orgtbl-hijacker-command-100
                            cua-delete-region
                            smex
                            isearch-other-control-char
                            tags-loop-continue
                            ace-jump-done
                            ace-jump-char-mode
                            save-thing-at-point
                            org-delete-char
                            ac-expand
                            isearch-other-meta-char
                            isearch-forward-regexp
                            rs-mark-paragraph
                            set-rectangular-region-anchor
                            switch-to-previous-buffer
                            cua-set-mark))

                            
                               